/**
 * docs/ — static site checks.
 *
 * The landing page has no build step and no framework, so nothing else would
 * catch the class of mistake it is actually prone to: a translation key added
 * to the markup and not to the dictionary, a FAQ answer edited on the page but
 * not in the structured data, a script that throws halfway and silently stops
 * every block after it, or a third-party URL creeping back in on a page whose
 * entire argument is that it makes no outside requests.
 *
 * Each page is parsed and its scripts are actually executed, because a syntax
 * check cannot catch a reference to a variable that no longer exists — that
 * exact bug once left the site blank below the header.
 *
 * Exit code 1 on any failure. Warnings do not fail the run.
 *
 *   node scripts/check-site.mjs
 */
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { JSDOM, VirtualConsole } from 'jsdom'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const DOCS = path.join(ROOT, 'docs')
// tr/index.html is generated by scripts/build-tr.mjs and checked like any other
// page — it is what an unfurler and a Turkish reader actually get, so a fault
// in it is not less real for being machine-written.
const PAGES = ['index.html', 'privacy.html', '404.html', 'tr/index.html']

const failures = []
const warnings = []
const fail = (page, msg) => failures.push(`${page}: ${msg}`)
const warn = (page, msg) => warnings.push(`${page}: ${msg}`)

const dictionary = readFileSync(path.join(DOCS, 'assets/js/i18n.js'), 'utf8')
/** Keys declared in the Turkish table, by their `    'key':` indentation. */
const declared = new Set([...dictionary.matchAll(/^ {4}'([\w.]+)':/gm)].map((m) => m[1]))

/** Loads a page, runs its scripts against a stubbed browser, returns the DOM. */
function render(page) {
  const html = readFileSync(path.join(DOCS, page), 'utf8')
  const errors = []
  const virtualConsole = new VirtualConsole()
  virtualConsole.on('jsdomError', (e) => errors.push(String(e)))

  const dom = new JSDOM(html, {
    runScripts: 'outside-only',
    pretendToBeVisual: true,
    virtualConsole,
    url: 'https://followlens.mtvrkan.com/',
  })
  const { window } = dom

  // The page's own feature detection expects these; jsdom has neither.
  window.matchMedia = () => ({ matches: false, addEventListener() {}, addListener() {} })
  window.IntersectionObserver = class {
    observe() {}
    unobserve() {}
    disconnect() {}
  }
  window.requestAnimationFrame = (fn) => setTimeout(() => fn(0), 0)

  // Resolved against the page's own directory, not against docs/: tr/index.html
  // reaches its scripts as ../assets/js/…, and joining that onto DOCS would
  // walk out of the site entirely.
  const here = path.dirname(path.join(DOCS, page))
  for (const src of [...html.matchAll(/<script src="([^"]+)"/g)].map((m) => m[1])) {
    try {
      window.eval(readFileSync(path.resolve(here, src), 'utf8'))
    } catch (e) {
      errors.push(`${src} threw: ${e.message}`)
    }
  }
  return { html, window, doc: window.document, errors }
}

for (const page of PAGES) {
  const { html, window, doc, errors } = render(page)
  const all = (sel) => [...doc.querySelectorAll(sel)]

  for (const e of errors) fail(page, `script error — ${e}`)

  // ── Translations ───────────────────────────────────────────────────────────
  // English lives in the markup and Turkish in the dictionary, so a key present
  // on the page but missing from the table shows as English inside a Turkish
  // paragraph — visible only to someone reading that language.
  const keys = all('[data-i18n], [data-i18n-html], [data-i18n-content]').map(
    (el) => el.dataset.i18n ?? el.dataset.i18nHtml ?? el.dataset.i18nContent,
  )
  for (const key of keys) if (!declared.has(key)) fail(page, `no Turkish for "${key}"`)

  // Switching language and back must leave the page in its original state.
  // Which way round that runs depends on the language the markup is already in:
  // on the generated Turkish page, switching *to* Turkish is a no-op by
  // definition, so it is switched to English and back instead. Testing it in
  // the wrong direction would report "changed nothing" on a page that is
  // working exactly as designed.
  const baked = doc.documentElement.getAttribute('data-lang') === 'tr' ? 'tr' : 'en'
  const other = baked === 'tr' ? 'en' : 'tr'
  const before = doc.body.textContent
  doc.querySelector(`[data-lang-btn="${other}"]`)?.click()
  const switched = doc.body.textContent
  doc.querySelector(`[data-lang-btn="${baked}"]`)?.click()
  if (keys.length && switched === before) fail(page, `switching to ${other === 'tr' ? 'Turkish' : 'English'} changed nothing`)
  if (doc.body.textContent !== before) fail(page, 'switching back did not restore the page')

  // ── No outside requests ────────────────────────────────────────────────────
  // The page claims nothing about the reader leaves their machine. A stylesheet,
  // font or script on another host contradicts that before the first paint.
  for (const el of all('link[href], script[src], img[src], iframe[src]')) {
    const url = el.getAttribute('href') ?? el.getAttribute('src')
    if (/^(https?:)?\/\//.test(url) && !url.startsWith('https://followlens.mtvrkan.com')) {
      fail(page, `external subresource — ${url}`)
    }
  }

  // ── Structure ──────────────────────────────────────────────────────────────
  if (all('h1').length !== 1) fail(page, `${all('h1').length} <h1>, expected exactly 1`)
  if (!all('main').length) fail(page, 'no <main>')
  if (!doc.documentElement.lang) fail(page, 'no lang on <html>')
  if (!doc.querySelector('meta[http-equiv="Content-Security-Policy"]')) fail(page, 'no CSP')
  if (!all('.skip-link').length) fail(page, 'no skip link')

  const levels = all('h1, h2, h3').map((h) => Number(h.tagName[1]))
  for (let i = 1; i < levels.length; i++) {
    if (levels[i] - levels[i - 1] > 1) fail(page, `heading jumps h${levels[i - 1]} → h${levels[i]}`)
  }

  // ── Accessibility ──────────────────────────────────────────────────────────
  for (const el of all('button, a')) {
    if (el.textContent.trim() || el.getAttribute('aria-label')) continue
    if (el.querySelector('svg')) fail(page, `icon-only ${el.tagName.toLowerCase()} with no aria-label`)
  }
  for (const img of all('img')) {
    if (!img.hasAttribute('alt')) fail(page, `<img src="${img.getAttribute('src')}"> has no alt`)
    if (!img.hasAttribute('width') && !img.hasAttribute('height')) {
      fail(page, `<img src="${img.getAttribute('src')}"> has no dimensions (CLS)`)
    }
  }

  // ── Metadata ───────────────────────────────────────────────────────────────
  const indexable = !/name="robots" content="[^"]*noindex/.test(html)
  if (indexable) {
    const desc = doc.querySelector('meta[name="description"]')?.getAttribute('content')
    if (!desc) fail(page, 'no meta description')
    // A search result is cut off past roughly this length, so anything after it
    // is written for nobody.
    else if (desc.length > 160) fail(page, `meta description is ${desc.length} chars, over 160`)
    if (!doc.querySelector('link[rel=canonical]')) fail(page, 'no canonical')
    if (!doc.querySelector('meta[property="og:image"]')) fail(page, 'no og:image')
    if (!doc.querySelector('meta[name="twitter:card"]')) fail(page, 'no twitter:card')
  }

  // ── Structured data ────────────────────────────────────────────────────────
  const ldNode = doc.querySelector('script[type="application/ld+json"]')
  if (ldNode) {
    let ld
    try {
      ld = JSON.parse(ldNode.textContent)
    } catch (e) {
      fail(page, `JSON-LD does not parse — ${e.message}`)
    }
    const faqLd = ld?.['@graph']?.find((n) => n['@type'] === 'FAQPage')?.mainEntity
    if (faqLd) {
      // Structured data that disagrees with the page is what FAQ markup gets
      // penalised for, and the two drift the moment one is edited alone.
      const onPage = all('.faq details').map((d) => ({
        q: d.querySelector('summary span').textContent.trim(),
        a: d.querySelector('p').textContent.trim(),
      }))
      if (onPage.length !== faqLd.length) {
        fail(page, `FAQ has ${onPage.length} entries, JSON-LD has ${faqLd.length}`)
      } else {
        onPage.forEach((entry, i) => {
          if (entry.q !== faqLd[i].name) fail(page, `FAQ question ${i + 1} differs from JSON-LD`)
          if (entry.a !== faqLd[i].acceptedAnswer.text) fail(page, `FAQ answer ${i + 1} differs from JSON-LD`)
        })
      }
    }
  }

  // ── Release gate ───────────────────────────────────────────────────────────
  // A warning rather than a failure: the page is meant to sit in this state
  // until the listing is published, and a permanently red build teaches people
  // to ignore the build.
  if (html.includes('CWS_EXTENSION_ID')) {
    warn(page, 'Chrome Web Store id is still the CWS_EXTENSION_ID placeholder — DO NOT DEPLOY')
  }

  window.close()
}

// Every translation must be reachable from some page, or it is dead weight that
// still has to be kept in step with the English.
const used = new Set(
  PAGES.flatMap((page) => {
    const doc = new JSDOM(readFileSync(path.join(DOCS, page), 'utf8')).window.document
    return [...doc.querySelectorAll('[data-i18n], [data-i18n-html], [data-i18n-content]')].map(
      (el) => el.dataset.i18n ?? el.dataset.i18nHtml ?? el.dataset.i18nContent,
    )
  }),
)
for (const key of declared) if (!used.has(key)) fail('i18n.js', `"${key}" is translated but used nowhere`)

for (const w of warnings) console.warn(`warning  ${w}`)
if (failures.length) {
  for (const f of failures) console.error(`FAIL     ${f}`)
  console.error(`\n${failures.length} problem${failures.length === 1 ? '' : 's'} in docs/`)
  process.exit(1)
}
console.log(`docs/ ok — ${PAGES.length} pages, ${declared.size} translations${warnings.length ? `, ${warnings.length} warning(s)` : ''}`)
